services:
  twitch-drops-miner:
    image: dungfu/twitch-drops-miner:16.dev.8c55d85
    container_name: twitch-drops-miner
    ports:
      - "5800:5800"
    volumes:
      - ./mishko/twitch_drops:/TwitchDropsMiner/config
      - ./mishko/twitch_drops:/TwitchDropsMiner/cache
    environment:
      - USER_ID=1000
      - GROUP_ID=1000
      - TZ=Europe/Prague
    restart: unless-stopped